services:
  - type: web
    name: help-desk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:///help-desk.db
      - key: FLASK_ENV
        value: production